// <auto-generated />
using System;
using BioWeb.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioWeb.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515011258_AddMissingProjectColumns")]
    partial class AddMissingProjectColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BioWeb.Server.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "israel.cyabu93@gmail.com",
                            FirstName = "Israel",
                            LastName = "Cyabukombe",
                            ProfilePhotoUrl = "/assets/IMG_0002.jpg",
                            SummaryText = "Full‑stack software engineer with 8 years of experience building enterprise healthcare applications in PHP (Laminas/Mezzio) and .NET, with expertise in senior care operations, document management, and designing automated reports that help stakeholders understand and act on their data."
                        });
                });

            modelBuilder.Entity("BioWeb.Server.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BioWeb.Server.Models.ProjectSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("BioWeb.Server.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "BackEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "BackEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 2,
                            SkillName = "PHP"
                        },
                        new
                        {
                            Id = 3,
                            Category = "BackEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 2,
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 4,
                            Category = "FrontEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 2,
                            SkillName = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Category = "FrameWork",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "React.js"
                        },
                        new
                        {
                            Id = 6,
                            Category = "FrontEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "CSS"
                        },
                        new
                        {
                            Id = 7,
                            Category = "FrontEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "Javascript"
                        },
                        new
                        {
                            Id = 8,
                            Category = "FrontEnd",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Other",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "Git"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Other",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "Git Extensions"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Other",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "RabbitMQ"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Other",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "Elastic"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Other",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "Jenkins"
                        },
                        new
                        {
                            Id = 14,
                            Category = "FrameWork",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "Laminas"
                        },
                        new
                        {
                            Id = 15,
                            Category = "FrameWork",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = ".Net"
                        });
                });

            modelBuilder.Entity("BioWeb.Server.Models.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            description = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            description = "Advanced"
                        });
                });

            modelBuilder.Entity("BioWeb.Server.Models.ProjectSkill", b =>
                {
                    b.HasOne("BioWeb.Server.Models.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioWeb.Server.Models.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BioWeb.Server.Models.Skill", b =>
                {
                    b.HasOne("BioWeb.Server.Models.PersonalInfo", "PersonalInfo")
                        .WithMany("Skills")
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioWeb.Server.Models.SkillLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("BioWeb.Server.Models.PersonalInfo", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("BioWeb.Server.Models.Project", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("BioWeb.Server.Models.Skill", b =>
                {
                    b.Navigation("ProjectSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
