// <auto-generated />
using BioWeb.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioWeb.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206212632_AddSkillCategory")]
    partial class AddSkillCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BioWeb.Server.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "israel.cyabu93@gmail.com",
                            FirstName = "Israel",
                            LastName = "Cyabukombe",
                            ProfilePhotoUrl = "/images/IMG_0002.jpg",
                            SummaryText = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos."
                        });
                });

            modelBuilder.Entity("BioWeb.Server.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            PersonalInfoId = 1,
                            SkillLevelId = 2,
                            SkillName = "PHP"
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            PersonalInfoId = 1,
                            SkillLevelId = 2,
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            PersonalInfoId = 1,
                            SkillLevelId = 2,
                            SkillName = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "React.js"
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            PersonalInfoId = 1,
                            SkillLevelId = 1,
                            SkillName = "CSS"
                        });
                });

            modelBuilder.Entity("BioWeb.Server.Models.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            description = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            description = "Advanced"
                        });
                });

            modelBuilder.Entity("BioWeb.Server.Models.Skill", b =>
                {
                    b.HasOne("BioWeb.Server.Models.PersonalInfo", "PersonalInfo")
                        .WithMany("Skills")
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioWeb.Server.Models.SkillLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("SkillLevel");
                });

            modelBuilder.Entity("BioWeb.Server.Models.PersonalInfo", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
